imgs_folder: D:\paper_repos\rd-gui\src

models:
  relatable_clothing:
    model_path: D:\paper_repos\rd-gui\src\pretrained_models\optimal_model\optimal_model.tar
    classes: D:\paper_repos\rd-gui\src\pretrained_models\optimal_model\objects_list.json
    relationships: D:\paper_repos\rd-gui\src\pretrained_models\optimal_model\pred_list.json
  vtranse:
    model_path: D:\paper_repos\rd-gui\src\pretrained_models\frcnn_vtranse\39_4312581_full_epoch.tar
    rd_model_path: D:\paper_repos\rd-gui\src\pretrained_models\first_rel_model\39_4312581_full_epoch.tar
    classes:  D:\paper_repos\rd-gui\src\pretrained_models\frcnn_vtranse\objects_list.json
    relationships: D:\paper_repos\rd-gui\src\pretrained_models\frcnn_vtranse\pred_list.json
    full_rd_model_kwargs:
        mrcnn_model_path: D:\paper_repos\rd-gui\src\pretrained_models\frcnn_vtranse\039resnet50_fpn_frcnn_full.tar
        min_size: 800
        max_size: 1333
        mask_mold_filters: 8
        num_classes: 201
        num_rel_classes: 100
        obj_score_thresh: 0.25
        FPN_filters: 256
        soft_attention_filters: 256
        hidden_layer_sizes:
            - 256
            - 128
            - 256
        pool_sizes:
            0: 50
            1: 25
            2: 12
            3: 12
            pool: 6
        bottleneck_filters: 16
        keys:
            - '0'
            - '1'
            - '2'
            - '3'
            - 'pool'